[versions]
agp = "9.0.1"
coreKtx = "1.17.0"
#junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
junitJupiter = "6.0.2"
appcompat = "1.7.1"
activity = "1.12.4"
constraintlayout = "2.2.1"
googleMaterial = "1.14.0-alpha09"
lifecycle = "2.10.0"
totpKt = "1.0.1"
commonsCodec = "1.21.0"
androidxSecurity = "1.1.0"
playServicesCodeScanner = "16.1.0"
protobuf = "4.33.5"
androidxBiometric = "1.4.0-alpha05"
#noinspection GradleDependency
ksp = "2.2.10-2.0.2"
room = "2.8.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
#androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
#androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
totp-kt = { group = "dev.robinohs", name = "totp-kt", version.ref = "totpKt" }
apache-commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidxSecurity" }
gms-play-services-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "playServicesCodeScanner" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidxBiometric" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-symbol-processing = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }